### ISSUE TITLE
Can this EFI work with macOS Ventura 13.3.1？

### ISSUE THREAD

**Issue by aya4dw** [girottos/EFI-Dell-Optiplex-7070-RX550-BCM94360-Ventura#1]
Can this EFI work with macOS Ventura 13.3.1？

**Comment by girottos** [comment]
> Can this EFI work with macOS Ventura 13.3.1？

I don't have the PC anymore, but you should update the opencore version before trying it.
According to Acidanthera's notes, there's nothing that would prevent you from (using a similar hardware).

**Comment by aya4dw** [comment]
I've tried to update 13.3.1, and it works well.
But the onboard audio card doesn't work, wharever I used my config or yours.
You can close this issues.

**Comment by girottos** [comment]
Thanks
